import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

// components
import NavBar from "../components/NavBar/NavBar";
import Drawer from "../components/Drawer/Drawer";
import HomeLayout from "../components/HomeLayout/HomeLayout";
import Counter from "../components/Counter/Counter";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Drawer />
      <HomeLayout />
    </div>
  );
}
